{{- if .Values.externalLoadBalancer }}
# /*
#  * Copyright (c) 2023 Software AG, Darmstadt, Germany and/or its licensors
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  *
#  *   Licensed under the Apache License, Version 2.0 (the "License");
#  *   you may not use this file except in compliance with the License.
#  *   You may obtain a copy of the License at
#  *
#  *       http://www.apache.org/licenses/LICENSE-2.0
#  *
#  *   Unless required by applicable law or agreed to in writing, software
#  *   distributed under the License is distributed on an "AS IS" BASIS,
#  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  *   See the License for the specific language governing permissions and
#  *   limitations under the License.
#  *
#  */

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservicesruntime.fullname" . }}-nginx
  labels:
    {{- include "microservicesruntime.labels" . | nindent 4 }}

data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log debug;
    pid        /var/run/nginx.pid;
     
    events {
        worker_connections  1024;
    }
     
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
      
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
     
        access_log  /var/log/nginx/access.log  main;
     
        sendfile        on;
        #tcp_nopush     on;
        keepalive_timeout  65;
        gzip  on;
     
        upstream msr-rt {
            server {{ include "microservicesruntime.fullname" . }}:{{ int .Values.microservicesruntime.runtimePort }};
        }
     
        upstream msr-admin {
            server {{ include "microservicesruntime.fullname" . }}:{{ int .Values.microservicesruntime.adminPort }};
        }
     
        server {
            listen {{ int .Values.microservicesruntime.runtimePort }};
            location / {
                proxy_pass http://msr-rt;
            }
        }
        
        server {
            listen {{ int .Values.microservicesruntime.adminPort }};
            location / {
                proxy_pass http://msr-admin;
            }
        }
    }
{{- end }}