# /*
#  * Copyright (c) 2023 Software AG, Darmstadt, Germany and/or its licensors
#  *
#  * SPDX-License-Identifier: Apache-2.0
#  *
#  *   Licensed under the Apache License, Version 2.0 (the "License");
#  *   you may not use this file except in compliance with the License.
#  *   You may obtain a copy of the License at
#  *
#  *       http://www.apache.org/licenses/LICENSE-2.0
#  *
#  *   Unless required by applicable law or agreed to in writing, software
#  *   distributed under the License is distributed on an "AS IS" BASIS,
#  *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  *   See the License for the specific language governing permissions and
#  *   limitations under the License.
#  *
#  */

apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservicesruntime.fullname" . }}
  labels:
    {{- include "microservicesruntime.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ int .Values.microservicesruntime.httpPort }}
    protocol: TCP
    targetPort: http
    name: http
    {{- if (eq .Values.service.type "ClusterIP") }}
    nodePort: null
    {{- end }}
  - port: {{ .Values.microservicesruntime.diagnosticPort }}
    protocol: TCP
    targetPort: diag
    name: diag
    {{- if (eq .Values.service.type "ClusterIP") }}
    nodePort: null
    {{- end }}
  - port: {{ .Values.microservicesruntime.httpsPort }}
    protocol: TCP
    targetPort: https
    name: https
    {{- if (eq .Values.service.type "ClusterIP") }}
    nodePort: null
    {{- end }}
  selector:
    {{- include "microservicesruntime.selectorLabels" . | nindent 4 }}
