
# Cron schedule syntax
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
# │ │ │ │ │                                   7 is also Sunday on some systems)
# │ │ │ │ │                                   OR sun, mon, tue, wed, thu, fri, sat
# │ │ │ │ │
# * * * * *

jobs:
# -- Implements a cron job to purge all auditing data which are older than 30 days.
- name: archive-auditing-data
  image:
    repository: ubuntu
    tag: latest
  imagePullPolicy: IfNotPresent
  restartPolicy: Never
  envFrom:
    - secretRef:
        name: msr-secrets
  # -- Schedule job every
  schedule: "* * * * *"
  command: ["/bin/bash"] 
  args:
    - -c
    - >-
        echo Archiving Auditing data with [${DEPLOYMENT}] ...;      
        apt-get update;
        apt-get install jq   -y;
        apt-get install curl -y;
        echo "Archiving Server data ..."
        curl -s -u "Administrator:${ADMIN_PASSWORD}" -H "Content-Type: application/json" "${DEPLOYMENT}:5555/invoke/pub.monitor.archive:serverArchive?days=30&archiveAction=DELETE&batchSize=100" | jq '.';
        echo "Archiving Process data ..."
        curl -s -u "Administrator:${ADMIN_PASSWORD}" -H "Content-Type: application/json" "${DEPLOYMENT}:5555/invoke/pub.monitor.archive:processArchive?days=30&archiveAction=DELETE&batchSize=100&status=COMPLETED-FAILED" | jq '.';
        echo "Archiving Services data ..."
        curl -s -u "Administrator:${ADMIN_PASSWORD}" -H "Content-Type: application/json" "${DEPLOYMENT}:5555/invoke/pub.monitor.archive:serviceArchive?days=30&archiveAction=DELETE&batchSize=100&status=COMPLETED-FAILED" | jq '.';
