jobs:
# Implements a job to configure the archiving
- name: configure-archiving
  annotations:
    # -- Start the job per Helm hook on `post-install` or `post-upgrade`
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
  image:
    repository: ubuntu
    tag: latest
  imagePullPolicy: IfNotPresent
  restartPolicy: Never
  envFrom:
    - secretRef:
        name: msr-secrets
  command: ["/bin/bash"] 
  args:
    - -c
    - >-
        echo Configure Archiving with [${DEPLOYMENT}] ...;
        apt-get update;
        apt-get install jq   -y;
        apt-get install curl -y;
        status=$(curl -s -o /dev/null -w "%{http_code}" ${DEPLOYMENT}:5555 -u "Administrator:${ADMIN_PASSWORD}");
        while [[ "${status}" != "200" ]];
        do 
          echo Waiting for IS [${DEPLOYMENT}] status [${status}] ...;
          sleep 10;
          status=$(curl -s -o /dev/null -w "%{http_code}" ${DEPLOYMENT}:5555 -u "Administrator:${ADMIN_PASSWORD}");
        done;
        curl -s -u "Administrator:${ADMIN_PASSWORD}" -H "Content-Type: application/json" "${DEPLOYMENT}:5555/invoke/pub.monitor.archive:setOperationParameters?ISCORE_SCHEMA=public&PROCESS_SCHEMA=public" | jq '.';
